palette = "noctalia"
add_newline = true
continuation_prompt = "[▸ ](dimmed white)"

format = """$directory$git_branch$git_status$fill$time
$character"""

[fill]
symbol = " "
style = "dimmed white"

[character]
success_symbol = "[ 󰅂](bold green)"
error_symbol = "[ 󰅂](bold red)"
vimcmd_symbol = "[❮](dimmed green)"

[directory]
home_symbol = "󰉋 "
read_only = "  "
style = "bold cyan"
format = "[$path]($style) "
truncation_length = 2
truncation_symbol = ".../"
substitutions = { "Desktop" = " ", "Documents" = " ", "Downloads" = " ", "Music" = "󰎈 ", "Pictures" = " ", "Videos" = " ", "GitHub" = "󰊤 " }

[git_branch]
format = "[$symbol $branch]($style) "
style = "bold purple"
symbol = " "

[git_status]
format = "[$all_status]($style)"
style = "bold yellow"
ahead = "⇡ "
behind = "⇣ "
diverged = "⇕ "
up_to_date = ""
untracked = " "
modified = " "
staged = " "
renamed = "󰜥 "
deleted = " "

[cmd_duration]
format = "[󰔚 $duration]($style) "
style = "dimmed white"
min_time = 2000
disabled = false

[time]
disabled = false
format = "[$time]($style)"
time_format = "%H:%M"
style = "dimmed white"
use_12hr = false

[package]
disabled = true
[git_commit]
disabled = true
[git_state]
disabled = true
[hostname]
disabled = true
[username]
disabled = true
[memory_usage]
disabled = true

# >>> NOCTALIA STARSHIP PALETTE >>>
# Noctalia Starship Palette
# Generated by Noctalia - do not edit manually

[palettes.noctalia]
# Standard colors
blue      = "#f6b8ab"
red       = "#ffb4ab"
green     = "#faacf9"
yellow    = "#d8bfd4"
cyan      = "#d8bfd4"
magenta   = "#faacf9"
white     = "#e2e2e2"
black     = "#474747"

# Extended palette (Catppuccin-compatible names)
rosewater = "#d8bfd4"
flamingo  = "#ffb4ab"
pink      = "#faacf9"
mauve     = "#faacf9"
maroon    = "#ffb4ab"
peach     = "#d8bfd4"
teal      = "#d8bfd4"
sky       = "#d8bfd4"
sapphire  = "#f6b8ab"
lavender  = "#faacf9"

# Text shades
text      = "#e2e2e2"
subtext1  = "#e2e2e2"
subtext0  = "#919191"

# Surface shades
overlay2  = "#919191"
overlay1  = "#919191"
overlay0  = "#474747"
surface2  = "#474747"
surface1  = "#474747"
surface0  = "#131313"
base      = "#131313"
mantle    = "#131313"
crust     = "#131313"
# <<< NOCTALIA STARSHIP PALETTE <<<
