[main]
# Твоя тема Noctalia
include=~/.config/foot/themes/noctalia

# Настройка шрифта (увеличили размер до 14)
font=JetBrainsMono Nerd Font:size=14
font-bold=JetBrainsMono Nerd Font:style=Bold:size=14
font-italic=JetBrainsMono Nerd Font:style=Italic:size=14
font-bold-italic=JetBrainsMono Nerd Font:style=Bold Italic:size=14

# Внутренние отступы
pad=8x8

# Тонкая настройка рендеринга
dpi-aware=yes
